name: Run Flax dependency tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_flax_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install "jax[cpu]>=0.2.16,!=0.3.2"
          pip install "flax>=0.4.1"
          pip install "jaxlib>=0.1.65"
          pip install pytest
      - name: Check for soft dependencies
        run: |
          pytest tests/others/test_dependencies.py
