name: Fast tests for PRs - PEFT backend

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DIFFUSERS_IS_CI: yes
  OMP_NUM_THREADS: 4
  MKL_NUM_THREADS: 4
  PYTEST_TIMEOUT: 60

jobs:
  run_fast_tests:
    strategy:
      fail-fast: false
      matrix:
        lib-versions: ["main", "latest"]


    name: LoRA - ${{ matrix.lib-versions }}

    runs-on: docker-cpu

    container:
      image: diffusers/diffusers-pytorch-cpu
      options: --shm-size "16gb" --ipc host -v /mnt/hf_cache:/mnt/cache/

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout diffusers
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install libsndfile1-dev libgl1 -y
        python -m pip install -e .[quality,test]
        if [ "${{ matrix.lib-versions }}" == "main" ]; then
            python -m pip install -U git+https://github.com/huggingface/peft.git
            python -m pip install -U git+https://github.com/huggingface/transformers.git
            python -m pip install -U git+https://github.com/huggingface/accelerate.git
        else
            python -m pip install -U peft transformers accelerate
        fi

    - name: Environment
      run: |
        python utils/print_env.py

    - name: Run fast PyTorch LoRA CPU tests with PEFT backend
      run: |
        python -m pytest -n 2 --max-worker-restart=0 --dist=loadfile \
          -s -v \
          --make-reports=tests_${{ matrix.config.report }} \
          tests/lora/test_lora_layers_peft.py
